### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by PopeFelix** [HakanKoseoglu/hamdocker#1]
Running elementary OS 5.1.7 Hera, Built on Ubuntu 18.04.4 LTS, Linux 4.15.0-143-generic, GTK 3.22.30

Docker version 19.03.13, build cd8016b6bc

When I attempt to start the container via `docker run -it --device /dev/snd:/dev/snd -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix:0 hakankoseoglu/wsjtx` (as recommended in the README) I get:

```
qt.qpa.xcb: could not connect to display unix:0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

I tried the fix listed [in the QT forum](https://forum.qt.io/post/624936) to no avail.

Any advice would be appreciated ASAP - I'm trying to use this for Field Day. 

73 de W0KEH

**Comment by HakanKoseoglu** [comment]
Try the xhost commands listed here:

https://github.com/jessfraz/dockerfiles/issues/329

One other possibility is your display is not runnng on :0 double-check your default DISPLAY variable and substitute accordingly.
